server:
  port: 9106
  servlet:
    context-path:
    session:
      timeout: 3600

sp:  
  base_url: http://localhost:9106
  # Entity ID of the SP
  entity_id: pilot_entity
  # Private key used to sign the SAML response
  private_key : MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCYzxyG0mZG6yaNJ1XbxpbpGo78APOkwZVDlImivmym4U/GjaF0c3R+KlV/P2G67arp3q80OY0H18Ihh9ksmAEsUnCprHsJlvZCprlnk1Fqruel82vFpEUU6VZ6oFtZ70U1lMx6BCoYbxH1wQ8ZgUlouLDjZZoMaHhHu3u+jbNsEX53gATV9Nm8nkh3+osYBduipSZ/hu3cUcBjRkXRfO3qJtMhCrbLT9qOCTCd1ZA+OnLRKLOvaJzA8ka7OXynBJeVmSBx2qn91k4Nupm3foDZMrFxX0FNG8cYyEFeE2KttTQxRlzAOhsqZtXBZ0HXHVJxDKy0PhKKqB6Me4INGU4lAgMBAAECggEAItBUzHaU7KVYVCJZEkgtS5BMcSd6WtfrvMjTjqtZr693cGIGHbTMHo5giiwThPXu0Xd1bS2LbvT9+ours9gxtDpYBqAQLAAjvM2lQe6zRt3wUsOhkxa40mnS1P9BsLythOaQq1/Vg1mSuu2wFfx5kA0756LXNOp8NMOHDsPT09PSV6PMcZI5g3Dpxl54zyCDotMePTXlV76uqakekJIowtnJvBL3KRc/cN8M7+fa1gktwc/P8FCi00jbBpunSqEjEpjRcSc+oon1nGNsyaZXcWfneNTD3uK8Gjl5gI3/wTWoeC3I1RjB2F45r6eZBGiFt1jzGm7xEi5d0kUPmOR9QQKBgQDLJN+gXp3k1Gf1fpuEmbuNHrfkUwNItqEch2YVlkatcz30bV0f83KQ9KPBcQDI8Vb62ogA2DOD5+ch6Co16M9X5ytxzpxnwydo/VImGM0DsooxSMU+H8ZeudpwWZx19f34K8KxASvgxdXkTczVihpV58IG/YFtSm+c/HVbGEkxNQKBgQDAkX8uG8VjvdaYzZPHdMB17Vd9u1n0bzFGqsHsM/+WDgnDHffpPmNA6+jFuf5yVDWdzcKZf1Ohf8WulLT0k6U7OmOrI/XJxLYyOu2m/JR+goSd+q6KbVPZACN4M/u+73utJoynqu8KlsRg/D+OrXIwtl94rt3HeKOhoYgZuIK3MQKBgHNBbXtwk0bkWENJ3PSDwIxVlGH/00orDAfCrmGrDFiWnN0UO5TILAUgN9Slx5s6im3zFNzdzYSWS2XKckB54UHvT4/XeJfKeo6vwy8IPTFO1+cUcYxIvOS7r7q0rPekZL6sHV8N2hZCSJOqrH+vRjfdMRGEPS2D4QWBmxffFI/NAoGAN1iaCRKKRQSG7RwI4Ua5GivA/a4fSJW8v+bMHatERkh6nc27NxprRHmJSWsPqqRxVI2S5LMnwj8K/gZXjAPzdXZutv164ybahs1RCLGHrGSu4QjvqXGKq8/SYfXu4Q3LqhRuULJcSdrTTlyxl7xaGY4RGoqHy5Ds1sOqbloNl8ECgYBFTsHyIzsBCIXusaFgXpvrefwDMbeJNfWG5pnSjyANDCO8Ob6GkM+gmSORO9sMwqnvYrHbcrezSnctxijeJsZr48iSJRghwMzdfPO61b9ntG2HQBlrEuQEzHn3SUEGI7jUxXUhgoaUYupPgOH48t7TtdQkGOg7p956p4yFx+Srtg==
  # Public certificate to verify the signature of the SAML response
  certificate: MIICwDCCAagCCQC5xppJazWl2DANBgkqhkiG9w0BAQsFADAiMSAwHgYDVQQKDBdPcmdhbml6YXRpb24sIENOPU11amluYTAeFw0yMDAzMTcwMjQxMzdaFw0zMDAzMTcwMjQxMzdaMCIxIDAeBgNVBAoMF09yZ2FuaXphdGlvbiwgQ049TXVqaW5hMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmM8chtJmRusmjSdV28aW6RqO/ADzpMGVQ5SJor5spuFPxo2hdHN0fipVfz9huu2q6d6vNDmNB9fCIYfZLJgBLFJwqax7CZb2Qqa5Z5NRaq7npfNrxaRFFOlWeqBbWe9FNZTMegQqGG8R9cEPGYFJaLiw42WaDGh4R7t7vo2zbBF+d4AE1fTZvJ5Id/qLGAXboqUmf4bt3FHAY0ZF0Xzt6ibTIQq2y0/ajgkwndWQPjpy0Sizr2icwPJGuzl8pwSXlZkgcdqp/dZODbqZt36A2TKxcV9BTRvHGMhBXhNirbU0MUZcwDobKmbVwWdB1x1ScQystD4SiqgejHuCDRlOJQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQBV4BrzOwdcTjUIjInEx52bckClyjn5g4tHiL42PSM4gQQQjHgDOpMFgoNjncR7rNYba8rI47dvLtHujhMrhq1Vkt0ExS3+rPeiARqv7c/KuCOh/mfAtsJOo3dGaVNdDoK6q/o2DkZAWot2SAEoCrHCiweO2Di2AL5Tcs2gDah4bw9Mgjptaz37LfhIsGsTMXHbttgbuBakeUmfWzBdpjHnO0hJ8vFYUS+nvOJNyEu1TLgR/dLgeGMgXze0eMEfYAvjPRfJ84ZRTHpSMLMHM/RgZjy7eLS/fnwgOQTeI/g3c3lvBKMNBL3cEbUgOv6CQve4CzgJGBrO9FXfiD1KEp00
  # Passphrase of the keystore
  passphrase: secret
  # Resource URL for the idp metadata
  idp_metadata_url: classpath:metadata/local-metadata.xml
  # SSO URL
  single_sign_on_service_location: http://localhost:9105/sso
  # ACS URL
  acs_location_path: /saml/SSO
  # Protocol binding
  protocol_binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST
  # authnRequest sining 여부
  needs_signing: true
  # endpoints 비교 할지 여부.
  compare_endpoints: true

logging:
  level:
    root: info
    saml.sample.sp: debug